import * as React from "react";
import Link from "next/link";
import type { ActivationReport } from "@/lib/activation";

// Phase 4 Slice B/D — activation widget for the dashboard.
//
// Replaces the old OnboardingChecklist. Three layers:
//
//   1. Activation score — big number + qualitative tier ("Early",
//      "Growing", …) + circular gauge. This is the signal: are you
//      actively using Flowtora?
//
//   2. Next best actions — up to three, ordered by impact. These are
//      generated by `pickActions` in src/lib/activation.ts based on
//      dimension gaps, so the copy and priority are ALWAYS relevant —
//      we never show "Add a customer" if the shop already has 20.
//
//   3. Full milestone checklist — collapsed behind a <details> so it's
//      available to users who still think in "6 of 6" terms but
//      doesn't dominate the widget. The NBA list above is the primary.
//
// The component is rendered as a server component (no interactivity)
// and anchors itself at #activation so the FinishSetupBanner can link
// directly to it.

const TIER_LABELS: Record<ActivationReport["tier"], string> = {
  new: "Getting started",
  early: "Early days",
  growing: "Picking up speed",
  established: "Running strong",
};

const TIER_BLURB: Record<ActivationReport["tier"], string> = {
  new: "You're just getting started. Pick the next step below to build momentum.",
  early: "The basics are in place. A few more actions and Flowtora starts compounding.",
  growing: "Nicely done — your workspace is operational. Keep pushing toward depth of use.",
  established: "You're running like a real shop. This widget will disappear soon.",
};

export function ActivationWidget({
  slug,
  report,
}: {
  slug: string;
  report: ActivationReport;
}) {
  return (
    <section
      id="activation"
      className="rounded-xl p-6"
      style={{
        background: "var(--surface-1)",
        border: "1px solid var(--border-subtle)",
      }}
    >
      <div className="flex flex-wrap items-start gap-6">
        <ScoreGauge score={report.score} tier={report.tier} />
        <div className="min-w-0 flex-1">
          <h2
            className="text-base font-semibold"
            style={{ color: "var(--text-default)" }}
          >
            Workspace activation · {TIER_LABELS[report.tier]}
          </h2>
          <p
            className="mt-1 text-sm"
            style={{ color: "var(--text-muted)" }}
          >
            {TIER_BLURB[report.tier]}
          </p>
        </div>
      </div>

      {report.actions.length > 0 && (
        <div className="mt-6">
          <div
            className="mb-2 text-[11px] font-semibold uppercase tracking-wider"
            style={{ color: "var(--text-faint)" }}
          >
            Recommended next steps
          </div>
          <div className="grid gap-2 md:grid-cols-3">
            {report.actions.map((a, i) => (
              <Link
                key={a.id}
                href={`/t/${slug}${a.href}`}
                className="flex flex-col justify-between rounded-lg px-3 py-3 transition-colors hover:brightness-110"
                style={{
                  background:
                    a.emphasis === "primary" && i === 0
                      ? "var(--accent-surface)"
                      : "var(--surface-0)",
                  border: `1px solid ${
                    a.emphasis === "primary" && i === 0
                      ? "var(--accent-surface-strong)"
                      : "var(--border-subtle)"
                  }`,
                }}
              >
                <div>
                  <div
                    className="text-sm font-medium"
                    style={{
                      color:
                        a.emphasis === "primary" && i === 0
                          ? "var(--accent-primary)"
                          : "var(--text-default)",
                    }}
                  >
                    {a.title}
                  </div>
                  <div
                    className="mt-1 text-xs leading-relaxed"
                    style={{ color: "var(--text-muted)" }}
                  >
                    {a.body}
                  </div>
                </div>
                <div
                  className="mt-3 text-[11px] font-semibold"
                  style={{
                    color:
                      a.emphasis === "primary" && i === 0
                        ? "var(--accent-primary)"
                        : "var(--text-muted)",
                  }}
                >
                  Go →
                </div>
              </Link>
            ))}
          </div>
        </div>
      )}

      <details className="mt-6">
        <summary
          className="cursor-pointer text-xs font-medium"
          style={{ color: "var(--text-muted)" }}
        >
          View the full milestone checklist
        </summary>
        <ul className="mt-3 grid gap-1.5 md:grid-cols-2">
          {report.milestones.map((m) => (
            <li key={m.key}>
              <Link
                href={`/t/${slug}${m.href}`}
                className="flex items-center gap-2 rounded-md px-2 py-1.5 text-xs transition-colors hover:brightness-110"
                style={{
                  background: "var(--surface-0)",
                  border: "1px solid var(--border-subtle)",
                  opacity: m.done ? 0.6 : 1,
                }}
              >
                <span
                  className="inline-flex h-4 w-4 shrink-0 items-center justify-center rounded-full text-[10px] font-bold"
                  style={{
                    background: m.done
                      ? "var(--success-surface)"
                      : "transparent",
                    color: m.done
                      ? "var(--success-fg)"
                      : "var(--text-faint)",
                    border: m.done
                      ? "1px solid var(--success-fg)"
                      : "1px solid var(--border-default)",
                  }}
                  aria-hidden
                >
                  {m.done ? "✓" : ""}
                </span>
                <span
                  style={{
                    color: m.done ? "var(--text-muted)" : "var(--text-default)",
                    textDecoration: m.done ? "line-through" : "none",
                  }}
                >
                  {m.label}
                </span>
              </Link>
            </li>
          ))}
        </ul>
      </details>
    </section>
  );
}

function ScoreGauge({
  score,
  tier,
}: {
  score: number;
  tier: ActivationReport["tier"];
}) {
  const size = 88;
  const stroke = 8;
  const r = (size - stroke) / 2;
  const c = 2 * Math.PI * r;
  const offset = c - (score / 100) * c;
  const color =
    tier === "established"
      ? "var(--success-fg)"
      : tier === "growing"
        ? "var(--accent-primary)"
        : tier === "early"
          ? "var(--accent-primary)"
          : "var(--warning-fg)";

  return (
    <div
      className="relative flex shrink-0 items-center justify-center"
      style={{ width: size, height: size }}
      aria-hidden
    >
      <svg width={size} height={size} className="-rotate-90">
        <circle
          cx={size / 2}
          cy={size / 2}
          r={r}
          fill="none"
          stroke="var(--border-default)"
          strokeWidth={stroke}
        />
        <circle
          cx={size / 2}
          cy={size / 2}
          r={r}
          fill="none"
          stroke={color}
          strokeWidth={stroke}
          strokeDasharray={c}
          strokeDashoffset={offset}
          strokeLinecap="round"
          style={{ transition: "stroke-dashoffset 300ms ease" }}
        />
      </svg>
      <div className="absolute flex flex-col items-center">
        <span
          className="text-lg font-semibold leading-none"
          style={{ color: "var(--text-default)" }}
        >
          {score}
        </span>
        <span
          className="mt-0.5 text-[10px] uppercase tracking-wider"
          style={{ color: "var(--text-faint)" }}
        >
          / 100
        </span>
      </div>
    </div>
  );
}
