import { requireTenant } from "@/lib/tenant";
import { db } from "@/lib/db";
import { Card, CardHeader } from "@/components/Card";
import { Button, Field, TextArea } from "@/components/Field";
import {
  requestDataExport,
  requestAccountDeletion,
  cancelAccountDeletionAsTenant,
} from "@/app/actions/compliance";
import { DELETION_GRACE_DAYS } from "@/lib/compliance";

// Phase 17 Slice E — tenant-owner compliance controls.
//
// Only the OWNER can see the destructive actions here; other roles see
// an "owner-only" notice. We deliberately isolate these into their own
// settings tab (rather than mixing into billing) so stumbling across the
// delete button requires an explicit navigation.

export default async function DangerZonePage({
  params,
  searchParams,
}: {
  params: Promise<{ slug: string }>;
  searchParams: Promise<{ error?: string; ok?: string }>;
}) {
  const { slug } = await params;
  const sp = await searchParams;
  const ctx = await requireTenant(slug);

  if (ctx.role !== "OWNER") {
    return (
      <Card>
        <CardHeader
          title="Danger zone"
          description="Account-level actions — only the owner can access these."
        />
        <p className="px-5 py-4 text-sm" style={{ color: "var(--text-muted)" }}>
          Ask your shop owner if you need to export or delete account data.
        </p>
      </Card>
    );
  }

  const [latestExport, scheduledDeletion] = await Promise.all([
    db.dataExportRequest.findFirst({
      where: { tenantId: ctx.tenant.id },
      orderBy: { createdAt: "desc" },
    }),
    db.accountDeletionRequest.findFirst({
      where: { tenantId: ctx.tenant.id, status: "SCHEDULED" },
    }),
  ]);

  const startExport = requestDataExport.bind(null, slug);
  const scheduleDelete = requestAccountDeletion.bind(null, slug);

  return (
    <div className="space-y-6">
      {sp.error && (
        <div
          className="rounded-md px-4 py-2 text-sm"
          style={{ background: "var(--danger-surface)", color: "var(--danger-fg)", border: "1px solid var(--danger-fg)" }}
        >
          {decodeURIComponent(sp.error)}
        </div>
      )}
      {sp.ok && (
        <div
          className="rounded-md px-4 py-2 text-sm"
          style={{ background: "var(--success-surface)", color: "var(--success-fg)", border: "1px solid var(--success-fg)" }}
        >
          {decodeURIComponent(sp.ok)}
        </div>
      )}

      {/* ── Data export ── */}
      <Card>
        <CardHeader
          title="Export all shop data"
          description="Generates a JSON bundle containing every customer, quote, order, invoice, file reference, and audit row tied to this shop."
        />
        <div className="space-y-3 px-5 py-4 text-sm">
          {latestExport ? (
            <ExportStatus req={latestExport} />
          ) : (
            <p style={{ color: "var(--text-muted)" }}>You haven&apos;t requested an export yet.</p>
          )}

          <form action={startExport}>
            <Button
              type="submit"
              disabled={
                !!(latestExport &&
                  (latestExport.status === "PENDING" ||
                    latestExport.status === "PROCESSING" ||
                    (latestExport.status === "COMPLETED" &&
                      latestExport.expiresAt &&
                      latestExport.expiresAt.getTime() > Date.now())))
              }
            >
              Request new export
            </Button>
          </form>
          <p className="text-xs" style={{ color: "var(--text-muted)" }}>
            Exports are generated by the Flowtora team within one business day. You&apos;ll see the download link here when it&apos;s ready. Download links expire after 7 days.
          </p>
        </div>
      </Card>

      {/* ── Account deletion ── */}
      <Card>
        <CardHeader
          title="Delete this account"
          description={`This schedules your shop for deletion ${DELETION_GRACE_DAYS} days from now. You can cancel any time during the grace period.`}
        />
        {scheduledDeletion ? (
          <div className="space-y-3 px-5 py-4 text-sm">
            <div
              className="rounded-md px-4 py-3"
              style={{ background: "var(--danger-surface)", color: "var(--danger-fg)", border: "1px solid var(--danger-fg)" }}
            >
              <div className="font-medium">Deletion scheduled</div>
              <div className="mt-0.5 text-xs">
                This account will be canceled on {scheduledDeletion.scheduledFor.toISOString().slice(0, 10)}.
              </div>
              {scheduledDeletion.reason && (
                <div className="mt-2 text-xs" style={{ color: "var(--text-muted)" }}>
                  Reason: {scheduledDeletion.reason}
                </div>
              )}
            </div>
            <form action={cancelAccountDeletionAsTenant.bind(null, slug, scheduledDeletion.id)}>
              <Button type="submit">Cancel deletion</Button>
            </form>
          </div>
        ) : (
          <form action={scheduleDelete} className="space-y-3 px-5 py-4">
            <div className="rounded-md px-3 py-2 text-xs" style={{ color: "var(--warning-fg, #ffc98b)", background: "var(--warning-surface, #3a2a15)", border: "1px solid var(--warning-fg, #5b4b20)" }}>
              <strong>This cannot be undone</strong> after the grace period expires. Every customer, quote, order, invoice, file, and user membership for this shop will be deleted. Consider running an export first.
            </div>
            <TextArea
              label="Reason (optional — helps us improve)"
              name="reason"
              rows={3}
              placeholder="e.g. Closing the shop, moving to a competitor, etc."
              maxLength={500}
            />
            <Field
              label={`Type your shop slug (${ctx.tenant.slug}) to confirm`}
              name="confirm"
              required
              placeholder={ctx.tenant.slug}
            />
            <Button type="submit" variant="danger">
              Schedule deletion in {DELETION_GRACE_DAYS} days
            </Button>
          </form>
        )}
      </Card>
    </div>
  );
}

function ExportStatus({ req }: { req: {
  id: string;
  status: string;
  createdAt: Date;
  completedAt: Date | null;
  expiresAt: Date | null;
  errorMessage: string | null;
} }) {
  const isReady = req.status === "COMPLETED" && req.expiresAt && req.expiresAt.getTime() > Date.now();
  return (
    <div className="rounded-md px-4 py-3" style={{ background: "var(--surface-1)", border: "1px solid var(--border-subtle)" }}>
      <div className="text-xs" style={{ color: "var(--text-muted)" }}>
        Last request: {req.createdAt.toISOString().slice(0, 10)} ·{" "}
        <span style={{
          color:
            req.status === "COMPLETED" ? "var(--success-fg)"
            : req.status === "FAILED" ? "var(--danger-fg)"
            : "var(--warning-fg, #ffc98b)",
        }}>
          {req.status.toLowerCase()}
        </span>
      </div>
      {isReady && (
        <a
          href={`/api/exports/${req.id}`}
          className="mt-2 inline-block text-sm font-medium underline"
        >
          Download bundle ({req.completedAt?.toISOString().slice(0, 10)})
        </a>
      )}
      {req.status === "COMPLETED" && req.expiresAt && req.expiresAt.getTime() < Date.now() && (
        <div className="mt-1 text-xs" style={{ color: "var(--text-muted)" }}>
          Download link expired. Request a new export below.
        </div>
      )}
      {req.status === "FAILED" && req.errorMessage && (
        <div className="mt-1 text-xs" style={{ color: "var(--danger-fg)" }}>
          {req.errorMessage}
        </div>
      )}
    </div>
  );
}
