import NextAuth from "next-auth";
import { NextResponse } from "next/server";
import { authConfig } from "@/auth.config";

// Phase 3.5 — middleware uses the edge-safe auth config.
//
// Importing from `@/auth` here pulls PrismaAdapter + the DB-backed
// `jwt` callback into the middleware bundle, which crashes at runtime
// because the Edge runtime can't execute Prisma Client without
// Accelerate or a driver adapter. `auth.config.ts` defines a
// providers-empty, DB-free config that's valid on Edge and still
// decodes the JWT cookie into `req.auth` so we can check authn here.
//
// The DB-backed revocation check still happens — it's wired in the
// full `auth.ts` config that server components, actions, and API
// routes import. Middleware is a first line of defense; the RSC layer
// is authoritative.

const { auth } = NextAuth(authConfig);

// Sprint 1 (Inbox consolidation) — 308 redirects for the five legacy
// routes that now live behind /t/[slug]/inbox chips. 308 (not 307) so
// browsers + CDNs cache the redirect permanently. Old links in emails,
// stored notifications, and anyone's bookmarks keep working.
//
// Query params are forwarded as-is and merged with the chip param. A
// link like /t/acme/messages?c=cus_123 becomes
// /t/acme/inbox?chip=messages&c=cus_123.
const INBOX_LEGACY_RE = /^\/t\/([^/]+)\/(attention|approvals|messages|notifications|tasks)\/?$/;

// Phase 3 (transformation) — customer detail collapsed the per-section
// routes (/edit, /timeline) into anchor targets on the main detail
// page. Old links + bookmarks keep working via 308: /edit lands on the
// page with the Contact inline-edit already scrolled into view;
// /timeline lands on the #activity anchor.
//
// Capture groups: slug, customer id, legacy segment (edit | timeline).
const CUSTOMER_LEGACY_RE = /^\/t\/([^/]+)\/customers\/([^/]+)\/(edit|timeline)\/?$/;

// Exact-match public paths. Anything in the marketing route group
// (src/app/(marketing)/…) needs to be listed here so unauthenticated
// visitors can actually navigate the site — previously only "/" was
// public, which redirected every cross-link (e.g. Home → Pricing) to
// /login.
const PUBLIC_PATHS = new Set<string>([
  "/",
  "/login",
  "/signup",
  "/account-suspended",
  "/maintenance",
  // Marketing pages
  "/about",
  "/book-demo",
  "/changelog",
  "/contact",
  "/features",
  "/for-print-shops",
  "/for-sign-shops",
  "/pricing",
  "/security",
  // File-based static routes generated by app/*.ts
  "/robots.txt",
  "/sitemap.xml",
]);

// Prefix-match public paths. Covers token-based flows (password
// reset, email verification, shared links) and any sub-routes of
// marketing sections like /legal/privacy or /legal/terms.
const PUBLIC_PREFIXES = [
  "/api/auth",
  "/api/webhooks",
  "/api/signup",
  "/api/track",        // First-party analytics beacon — public visitors
  "/api/consent",      // GDPR consent audit log — public visitors
  "/accept-invite",
  "/_next",
  "/favicon",
  "/legal",
  "/reset",
  "/verify",
  "/q/",
  "/share/",
];

export default auth((req) => {
  const { pathname } = req.nextUrl;
  const session = req.auth;

  // Legacy inbox route redirects — handled before auth so an unauthed
  // user bookmarking /t/foo/messages gets bounced to /inbox first, then
  // login with the correct `next=` pointer. Permanent 308 so CDNs cache.
  const legacyMatch = pathname.match(INBOX_LEGACY_RE);
  if (legacyMatch) {
    const [, slug, chip] = legacyMatch;
    const url = req.nextUrl.clone();
    url.pathname = `/t/${slug}/inbox`;
    url.searchParams.set("chip", chip);
    return NextResponse.redirect(url, 308);
  }

  // Phase 3 (transformation) — /customers/[id]/edit and /timeline are
  // collapsed into anchor targets on the parent detail page.
  // /edit → #overview (inline-edit cards live there)
  // /timeline → #activity (unified TimelineStream)
  // NOTE: fragments (#…) are not sent to the server, but NextResponse
  // preserves them in the Location header so the browser scrolls to
  // the right spot. We set it via the url object's `hash` property.
  const customerLegacyMatch = pathname.match(CUSTOMER_LEGACY_RE);
  if (customerLegacyMatch) {
    const [, slug, cid, kind] = customerLegacyMatch;
    const url = req.nextUrl.clone();
    url.pathname = `/t/${slug}/customers/${cid}`;
    url.hash = kind === "timeline" ? "activity" : "overview";
    return NextResponse.redirect(url, 308);
  }

  // Forward the pathname so server components / layouts can read it.
  const requestHeaders = new Headers(req.headers);
  requestHeaders.set("x-pathname", pathname);
  const passthrough = NextResponse.next({ request: { headers: requestHeaders } });

  const isPublic =
    PUBLIC_PATHS.has(pathname) ||
    PUBLIC_PREFIXES.some((p) => pathname.startsWith(p));

  if (isPublic) return passthrough;

  if (!session?.user) {
    const url = req.nextUrl.clone();
    url.pathname = "/login";
    url.searchParams.set("next", pathname);
    return NextResponse.redirect(url);
  }

  // Platform area is gated to platform staff only.
  if (pathname.startsWith("/platform") && !session.user.platformRole) {
    return NextResponse.redirect(new URL("/select-tenant", req.url));
  }

  return passthrough;
});

export const config = {
  // Skip middleware on:
  //   • Next internals (_next/static, _next/image)
  //   • The legacy favicon.ico path
  //   • Anything ending in a common static-asset extension (images,
  //     fonts, manifests, sourcemaps, etc.) so files dropped into
  //     /public/ — like the brand logo PNGs — are served directly
  //     instead of being treated as authenticated app routes and
  //     307-redirected to /login for visitors on public pages.
  matcher: [
    "/((?!_next/static|_next/image|favicon.ico|.*\\.(?:png|jpg|jpeg|gif|svg|webp|ico|avif|css|js|woff|woff2|ttf|otf|map|webmanifest|txt)$).*)",
  ],
};
