import NextAuth from "next-auth";
import { NextResponse } from "next/server";
import { authConfig } from "@/auth.config";

// Phase 3.5 — middleware uses the edge-safe auth config.
//
// Importing from `@/auth` here pulls PrismaAdapter + the DB-backed
// `jwt` callback into the middleware bundle, which crashes at runtime
// because the Edge runtime can't execute Prisma Client without
// Accelerate or a driver adapter. `auth.config.ts` defines a
// providers-empty, DB-free config that's valid on Edge and still
// decodes the JWT cookie into `req.auth` so we can check authn here.
//
// The DB-backed revocation check still happens — it's wired in the
// full `auth.ts` config that server components, actions, and API
// routes import. Middleware is a first line of defense; the RSC layer
// is authoritative.

const { auth } = NextAuth(authConfig);

// Exact-match public paths. Anything in the marketing route group
// (src/app/(marketing)/…) needs to be listed here so unauthenticated
// visitors can actually navigate the site — previously only "/" was
// public, which redirected every cross-link (e.g. Home → Pricing) to
// /login.
const PUBLIC_PATHS = new Set<string>([
  "/",
  "/login",
  "/signup",
  "/account-suspended",
  // Marketing pages
  "/about",
  "/book-demo",
  "/changelog",
  "/contact",
  "/features",
  "/for-print-shops",
  "/for-sign-shops",
  "/pricing",
  "/security",
  // File-based static routes generated by app/*.ts
  "/robots.txt",
  "/sitemap.xml",
]);

// Prefix-match public paths. Covers token-based flows (password
// reset, email verification, shared links) and any sub-routes of
// marketing sections like /legal/privacy or /legal/terms.
const PUBLIC_PREFIXES = [
  "/api/auth",
  "/api/webhooks",
  "/accept-invite",
  "/_next",
  "/favicon",
  "/legal",
  "/reset",
  "/verify",
  "/q/",
  "/share/",
];

export default auth((req) => {
  const { pathname } = req.nextUrl;
  const session = req.auth;

  // Forward the pathname so server components / layouts can read it.
  const requestHeaders = new Headers(req.headers);
  requestHeaders.set("x-pathname", pathname);
  const passthrough = NextResponse.next({ request: { headers: requestHeaders } });

  const isPublic =
    PUBLIC_PATHS.has(pathname) ||
    PUBLIC_PREFIXES.some((p) => pathname.startsWith(p));

  if (isPublic) return passthrough;

  if (!session?.user) {
    const url = req.nextUrl.clone();
    url.pathname = "/login";
    url.searchParams.set("next", pathname);
    return NextResponse.redirect(url);
  }

  // Platform area is gated to platform staff only.
  if (pathname.startsWith("/platform") && !session.user.platformRole) {
    return NextResponse.redirect(new URL("/select-tenant", req.url));
  }

  return passthrough;
});

export const config = {
  matcher: ["/((?!_next/static|_next/image|favicon.ico).*)"],
};
